// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: segment.proto

package protobuf;

public final class SegmentPB {
  private SegmentPB() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface SegmentOrBuilder extends
      // @@protoc_insertion_point(interface_extends:protobuf.Segment)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required .protobuf.Segment.SegmentType type = 1 [default = NONE];</code>
     */
    boolean hasType();
    /**
     * <code>required .protobuf.Segment.SegmentType type = 1 [default = NONE];</code>
     */
    protobuf.SegmentPB.Segment.SegmentType getType();

    /**
     * <code>required string sender = 2 [default = "0"];</code>
     */
    boolean hasSender();
    /**
     * <code>required string sender = 2 [default = "0"];</code>
     */
    java.lang.String getSender();
    /**
     * <code>required string sender = 2 [default = "0"];</code>
     */
    com.google.protobuf.ByteString
        getSenderBytes();

    /**
     * <code>required string receiver = 3 [default = "1"];</code>
     */
    boolean hasReceiver();
    /**
     * <code>required string receiver = 3 [default = "1"];</code>
     */
    java.lang.String getReceiver();
    /**
     * <code>required string receiver = 3 [default = "1"];</code>
     */
    com.google.protobuf.ByteString
        getReceiverBytes();

    /**
     * <code>required string data = 4 [default = "0"];</code>
     */
    boolean hasData();
    /**
     * <code>required string data = 4 [default = "0"];</code>
     */
    java.lang.String getData();
    /**
     * <code>required string data = 4 [default = "0"];</code>
     */
    com.google.protobuf.ByteString
        getDataBytes();

    /**
     * <code>required string dchecksum = 5 [default = "0"];</code>
     */
    boolean hasDchecksum();
    /**
     * <code>required string dchecksum = 5 [default = "0"];</code>
     */
    java.lang.String getDchecksum();
    /**
     * <code>required string dchecksum = 5 [default = "0"];</code>
     */
    com.google.protobuf.ByteString
        getDchecksumBytes();

    /**
     * <code>required string signature = 6 [default = "0"];</code>
     */
    boolean hasSignature();
    /**
     * <code>required string signature = 6 [default = "0"];</code>
     */
    java.lang.String getSignature();
    /**
     * <code>required string signature = 6 [default = "0"];</code>
     */
    com.google.protobuf.ByteString
        getSignatureBytes();

    /**
     * <code>required string schecksum = 7 [default = "0"];</code>
     */
    boolean hasSchecksum();
    /**
     * <code>required string schecksum = 7 [default = "0"];</code>
     */
    java.lang.String getSchecksum();
    /**
     * <code>required string schecksum = 7 [default = "0"];</code>
     */
    com.google.protobuf.ByteString
        getSchecksumBytes();

    /**
     * <code>optional string pubkey = 8;</code>
     */
    boolean hasPubkey();
    /**
     * <code>optional string pubkey = 8;</code>
     */
    java.lang.String getPubkey();
    /**
     * <code>optional string pubkey = 8;</code>
     */
    com.google.protobuf.ByteString
        getPubkeyBytes();

    /**
     * <code>optional string verkey = 9;</code>
     */
    boolean hasVerkey();
    /**
     * <code>optional string verkey = 9;</code>
     */
    java.lang.String getVerkey();
    /**
     * <code>optional string verkey = 9;</code>
     */
    com.google.protobuf.ByteString
        getVerkeyBytes();

    /**
     * <code>optional string length = 10;</code>
     */
    boolean hasLength();
    /**
     * <code>optional string length = 10;</code>
     */
    java.lang.String getLength();
    /**
     * <code>optional string length = 10;</code>
     */
    com.google.protobuf.ByteString
        getLengthBytes();

    /**
     * <code>optional string identifier = 11;</code>
     */
    boolean hasIdentifier();
    /**
     * <code>optional string identifier = 11;</code>
     */
    java.lang.String getIdentifier();
    /**
     * <code>optional string identifier = 11;</code>
     */
    com.google.protobuf.ByteString
        getIdentifierBytes();
  }
  /**
   * Protobuf type {@code protobuf.Segment}
   */
  public  static final class Segment extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:protobuf.Segment)
      SegmentOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Segment.newBuilder() to construct.
    private Segment(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Segment() {
      type_ = 0;
      sender_ = "0";
      receiver_ = "1";
      data_ = "0";
      dchecksum_ = "0";
      signature_ = "0";
      schecksum_ = "0";
      pubkey_ = "";
      verkey_ = "";
      length_ = "";
      identifier_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Segment(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              int rawValue = input.readEnum();
                @SuppressWarnings("deprecation")
              protobuf.SegmentPB.Segment.SegmentType value = protobuf.SegmentPB.Segment.SegmentType.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(1, rawValue);
              } else {
                bitField0_ |= 0x00000001;
                type_ = rawValue;
              }
              break;
            }
            case 18: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000002;
              sender_ = bs;
              break;
            }
            case 26: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000004;
              receiver_ = bs;
              break;
            }
            case 34: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000008;
              data_ = bs;
              break;
            }
            case 42: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000010;
              dchecksum_ = bs;
              break;
            }
            case 50: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000020;
              signature_ = bs;
              break;
            }
            case 58: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000040;
              schecksum_ = bs;
              break;
            }
            case 66: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000080;
              pubkey_ = bs;
              break;
            }
            case 74: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000100;
              verkey_ = bs;
              break;
            }
            case 82: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000200;
              length_ = bs;
              break;
            }
            case 90: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000400;
              identifier_ = bs;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return protobuf.SegmentPB.internal_static_protobuf_Segment_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return protobuf.SegmentPB.internal_static_protobuf_Segment_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              protobuf.SegmentPB.Segment.class, protobuf.SegmentPB.Segment.Builder.class);
    }

    /**
     * Protobuf enum {@code protobuf.Segment.SegmentType}
     */
    public enum SegmentType
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>NONE = 0;</code>
       */
      NONE(0),
      /**
       * <code>NEXT = 1;</code>
       */
      NEXT(1),
      /**
       * <code>ERROR = 12;</code>
       */
      ERROR(12),
      /**
       * <code>ACCEPT = 2;</code>
       */
      ACCEPT(2),
      /**
       * <code>REJECT = 3;</code>
       */
      REJECT(3),
      /**
       * <code>REQUEST_CONNECT = 4;</code>
       */
      REQUEST_CONNECT(4),
      /**
       * <code>DISCONNECT = 5;</code>
       */
      DISCONNECT(5),
      /**
       * <code>REQUEST_KEY = 6;</code>
       */
      REQUEST_KEY(6),
      /**
       * <code>SEND_KEY = 7;</code>
       */
      SEND_KEY(7),
      /**
       * <code>SEND_MESSAGE = 8;</code>
       */
      SEND_MESSAGE(8),
      /**
       * <code>SEND_FILE = 9;</code>
       */
      SEND_FILE(9),
      /**
       * <code>REQUEST_SEND_MESSAGE = 10;</code>
       */
      REQUEST_SEND_MESSAGE(10),
      /**
       * <code>REQUEST_SEND_FILE = 11;</code>
       */
      REQUEST_SEND_FILE(11),
      ;

      /**
       * <code>NONE = 0;</code>
       */
      public static final int NONE_VALUE = 0;
      /**
       * <code>NEXT = 1;</code>
       */
      public static final int NEXT_VALUE = 1;
      /**
       * <code>ERROR = 12;</code>
       */
      public static final int ERROR_VALUE = 12;
      /**
       * <code>ACCEPT = 2;</code>
       */
      public static final int ACCEPT_VALUE = 2;
      /**
       * <code>REJECT = 3;</code>
       */
      public static final int REJECT_VALUE = 3;
      /**
       * <code>REQUEST_CONNECT = 4;</code>
       */
      public static final int REQUEST_CONNECT_VALUE = 4;
      /**
       * <code>DISCONNECT = 5;</code>
       */
      public static final int DISCONNECT_VALUE = 5;
      /**
       * <code>REQUEST_KEY = 6;</code>
       */
      public static final int REQUEST_KEY_VALUE = 6;
      /**
       * <code>SEND_KEY = 7;</code>
       */
      public static final int SEND_KEY_VALUE = 7;
      /**
       * <code>SEND_MESSAGE = 8;</code>
       */
      public static final int SEND_MESSAGE_VALUE = 8;
      /**
       * <code>SEND_FILE = 9;</code>
       */
      public static final int SEND_FILE_VALUE = 9;
      /**
       * <code>REQUEST_SEND_MESSAGE = 10;</code>
       */
      public static final int REQUEST_SEND_MESSAGE_VALUE = 10;
      /**
       * <code>REQUEST_SEND_FILE = 11;</code>
       */
      public static final int REQUEST_SEND_FILE_VALUE = 11;


      public final int getNumber() {
        return value;
      }

      /**
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @java.lang.Deprecated
      public static SegmentType valueOf(int value) {
        return forNumber(value);
      }

      public static SegmentType forNumber(int value) {
        switch (value) {
          case 0: return NONE;
          case 1: return NEXT;
          case 12: return ERROR;
          case 2: return ACCEPT;
          case 3: return REJECT;
          case 4: return REQUEST_CONNECT;
          case 5: return DISCONNECT;
          case 6: return REQUEST_KEY;
          case 7: return SEND_KEY;
          case 8: return SEND_MESSAGE;
          case 9: return SEND_FILE;
          case 10: return REQUEST_SEND_MESSAGE;
          case 11: return REQUEST_SEND_FILE;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<SegmentType>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static final com.google.protobuf.Internal.EnumLiteMap<
          SegmentType> internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<SegmentType>() {
              public SegmentType findValueByNumber(int number) {
                return SegmentType.forNumber(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(ordinal());
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return protobuf.SegmentPB.Segment.getDescriptor().getEnumTypes().get(0);
      }

      private static final SegmentType[] VALUES = values();

      public static SegmentType valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        return VALUES[desc.getIndex()];
      }

      private final int value;

      private SegmentType(int value) {
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:protobuf.Segment.SegmentType)
    }

    private int bitField0_;
    public static final int TYPE_FIELD_NUMBER = 1;
    private int type_;
    /**
     * <code>required .protobuf.Segment.SegmentType type = 1 [default = NONE];</code>
     */
    public boolean hasType() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required .protobuf.Segment.SegmentType type = 1 [default = NONE];</code>
     */
    public protobuf.SegmentPB.Segment.SegmentType getType() {
      @SuppressWarnings("deprecation")
      protobuf.SegmentPB.Segment.SegmentType result = protobuf.SegmentPB.Segment.SegmentType.valueOf(type_);
      return result == null ? protobuf.SegmentPB.Segment.SegmentType.NONE : result;
    }

    public static final int SENDER_FIELD_NUMBER = 2;
    private volatile java.lang.Object sender_;
    /**
     * <code>required string sender = 2 [default = "0"];</code>
     */
    public boolean hasSender() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required string sender = 2 [default = "0"];</code>
     */
    public java.lang.String getSender() {
      java.lang.Object ref = sender_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          sender_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string sender = 2 [default = "0"];</code>
     */
    public com.google.protobuf.ByteString
        getSenderBytes() {
      java.lang.Object ref = sender_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        sender_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int RECEIVER_FIELD_NUMBER = 3;
    private volatile java.lang.Object receiver_;
    /**
     * <code>required string receiver = 3 [default = "1"];</code>
     */
    public boolean hasReceiver() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>required string receiver = 3 [default = "1"];</code>
     */
    public java.lang.String getReceiver() {
      java.lang.Object ref = receiver_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          receiver_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string receiver = 3 [default = "1"];</code>
     */
    public com.google.protobuf.ByteString
        getReceiverBytes() {
      java.lang.Object ref = receiver_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        receiver_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int DATA_FIELD_NUMBER = 4;
    private volatile java.lang.Object data_;
    /**
     * <code>required string data = 4 [default = "0"];</code>
     */
    public boolean hasData() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>required string data = 4 [default = "0"];</code>
     */
    public java.lang.String getData() {
      java.lang.Object ref = data_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          data_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string data = 4 [default = "0"];</code>
     */
    public com.google.protobuf.ByteString
        getDataBytes() {
      java.lang.Object ref = data_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        data_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int DCHECKSUM_FIELD_NUMBER = 5;
    private volatile java.lang.Object dchecksum_;
    /**
     * <code>required string dchecksum = 5 [default = "0"];</code>
     */
    public boolean hasDchecksum() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <code>required string dchecksum = 5 [default = "0"];</code>
     */
    public java.lang.String getDchecksum() {
      java.lang.Object ref = dchecksum_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          dchecksum_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string dchecksum = 5 [default = "0"];</code>
     */
    public com.google.protobuf.ByteString
        getDchecksumBytes() {
      java.lang.Object ref = dchecksum_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        dchecksum_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int SIGNATURE_FIELD_NUMBER = 6;
    private volatile java.lang.Object signature_;
    /**
     * <code>required string signature = 6 [default = "0"];</code>
     */
    public boolean hasSignature() {
      return ((bitField0_ & 0x00000020) == 0x00000020);
    }
    /**
     * <code>required string signature = 6 [default = "0"];</code>
     */
    public java.lang.String getSignature() {
      java.lang.Object ref = signature_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          signature_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string signature = 6 [default = "0"];</code>
     */
    public com.google.protobuf.ByteString
        getSignatureBytes() {
      java.lang.Object ref = signature_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        signature_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int SCHECKSUM_FIELD_NUMBER = 7;
    private volatile java.lang.Object schecksum_;
    /**
     * <code>required string schecksum = 7 [default = "0"];</code>
     */
    public boolean hasSchecksum() {
      return ((bitField0_ & 0x00000040) == 0x00000040);
    }
    /**
     * <code>required string schecksum = 7 [default = "0"];</code>
     */
    public java.lang.String getSchecksum() {
      java.lang.Object ref = schecksum_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          schecksum_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string schecksum = 7 [default = "0"];</code>
     */
    public com.google.protobuf.ByteString
        getSchecksumBytes() {
      java.lang.Object ref = schecksum_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        schecksum_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int PUBKEY_FIELD_NUMBER = 8;
    private volatile java.lang.Object pubkey_;
    /**
     * <code>optional string pubkey = 8;</code>
     */
    public boolean hasPubkey() {
      return ((bitField0_ & 0x00000080) == 0x00000080);
    }
    /**
     * <code>optional string pubkey = 8;</code>
     */
    public java.lang.String getPubkey() {
      java.lang.Object ref = pubkey_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          pubkey_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string pubkey = 8;</code>
     */
    public com.google.protobuf.ByteString
        getPubkeyBytes() {
      java.lang.Object ref = pubkey_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        pubkey_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int VERKEY_FIELD_NUMBER = 9;
    private volatile java.lang.Object verkey_;
    /**
     * <code>optional string verkey = 9;</code>
     */
    public boolean hasVerkey() {
      return ((bitField0_ & 0x00000100) == 0x00000100);
    }
    /**
     * <code>optional string verkey = 9;</code>
     */
    public java.lang.String getVerkey() {
      java.lang.Object ref = verkey_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          verkey_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string verkey = 9;</code>
     */
    public com.google.protobuf.ByteString
        getVerkeyBytes() {
      java.lang.Object ref = verkey_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        verkey_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int LENGTH_FIELD_NUMBER = 10;
    private volatile java.lang.Object length_;
    /**
     * <code>optional string length = 10;</code>
     */
    public boolean hasLength() {
      return ((bitField0_ & 0x00000200) == 0x00000200);
    }
    /**
     * <code>optional string length = 10;</code>
     */
    public java.lang.String getLength() {
      java.lang.Object ref = length_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          length_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string length = 10;</code>
     */
    public com.google.protobuf.ByteString
        getLengthBytes() {
      java.lang.Object ref = length_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        length_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int IDENTIFIER_FIELD_NUMBER = 11;
    private volatile java.lang.Object identifier_;
    /**
     * <code>optional string identifier = 11;</code>
     */
    public boolean hasIdentifier() {
      return ((bitField0_ & 0x00000400) == 0x00000400);
    }
    /**
     * <code>optional string identifier = 11;</code>
     */
    public java.lang.String getIdentifier() {
      java.lang.Object ref = identifier_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          identifier_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string identifier = 11;</code>
     */
    public com.google.protobuf.ByteString
        getIdentifierBytes() {
      java.lang.Object ref = identifier_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        identifier_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasType()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasSender()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasReceiver()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasData()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasDchecksum()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasSignature()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasSchecksum()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeEnum(1, type_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, sender_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, receiver_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, data_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 5, dchecksum_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 6, signature_);
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 7, schecksum_);
      }
      if (((bitField0_ & 0x00000080) == 0x00000080)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 8, pubkey_);
      }
      if (((bitField0_ & 0x00000100) == 0x00000100)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 9, verkey_);
      }
      if (((bitField0_ & 0x00000200) == 0x00000200)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 10, length_);
      }
      if (((bitField0_ & 0x00000400) == 0x00000400)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 11, identifier_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, type_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, sender_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, receiver_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, data_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, dchecksum_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(6, signature_);
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(7, schecksum_);
      }
      if (((bitField0_ & 0x00000080) == 0x00000080)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(8, pubkey_);
      }
      if (((bitField0_ & 0x00000100) == 0x00000100)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(9, verkey_);
      }
      if (((bitField0_ & 0x00000200) == 0x00000200)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(10, length_);
      }
      if (((bitField0_ & 0x00000400) == 0x00000400)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(11, identifier_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof protobuf.SegmentPB.Segment)) {
        return super.equals(obj);
      }
      protobuf.SegmentPB.Segment other = (protobuf.SegmentPB.Segment) obj;

      boolean result = true;
      result = result && (hasType() == other.hasType());
      if (hasType()) {
        result = result && type_ == other.type_;
      }
      result = result && (hasSender() == other.hasSender());
      if (hasSender()) {
        result = result && getSender()
            .equals(other.getSender());
      }
      result = result && (hasReceiver() == other.hasReceiver());
      if (hasReceiver()) {
        result = result && getReceiver()
            .equals(other.getReceiver());
      }
      result = result && (hasData() == other.hasData());
      if (hasData()) {
        result = result && getData()
            .equals(other.getData());
      }
      result = result && (hasDchecksum() == other.hasDchecksum());
      if (hasDchecksum()) {
        result = result && getDchecksum()
            .equals(other.getDchecksum());
      }
      result = result && (hasSignature() == other.hasSignature());
      if (hasSignature()) {
        result = result && getSignature()
            .equals(other.getSignature());
      }
      result = result && (hasSchecksum() == other.hasSchecksum());
      if (hasSchecksum()) {
        result = result && getSchecksum()
            .equals(other.getSchecksum());
      }
      result = result && (hasPubkey() == other.hasPubkey());
      if (hasPubkey()) {
        result = result && getPubkey()
            .equals(other.getPubkey());
      }
      result = result && (hasVerkey() == other.hasVerkey());
      if (hasVerkey()) {
        result = result && getVerkey()
            .equals(other.getVerkey());
      }
      result = result && (hasLength() == other.hasLength());
      if (hasLength()) {
        result = result && getLength()
            .equals(other.getLength());
      }
      result = result && (hasIdentifier() == other.hasIdentifier());
      if (hasIdentifier()) {
        result = result && getIdentifier()
            .equals(other.getIdentifier());
      }
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasType()) {
        hash = (37 * hash) + TYPE_FIELD_NUMBER;
        hash = (53 * hash) + type_;
      }
      if (hasSender()) {
        hash = (37 * hash) + SENDER_FIELD_NUMBER;
        hash = (53 * hash) + getSender().hashCode();
      }
      if (hasReceiver()) {
        hash = (37 * hash) + RECEIVER_FIELD_NUMBER;
        hash = (53 * hash) + getReceiver().hashCode();
      }
      if (hasData()) {
        hash = (37 * hash) + DATA_FIELD_NUMBER;
        hash = (53 * hash) + getData().hashCode();
      }
      if (hasDchecksum()) {
        hash = (37 * hash) + DCHECKSUM_FIELD_NUMBER;
        hash = (53 * hash) + getDchecksum().hashCode();
      }
      if (hasSignature()) {
        hash = (37 * hash) + SIGNATURE_FIELD_NUMBER;
        hash = (53 * hash) + getSignature().hashCode();
      }
      if (hasSchecksum()) {
        hash = (37 * hash) + SCHECKSUM_FIELD_NUMBER;
        hash = (53 * hash) + getSchecksum().hashCode();
      }
      if (hasPubkey()) {
        hash = (37 * hash) + PUBKEY_FIELD_NUMBER;
        hash = (53 * hash) + getPubkey().hashCode();
      }
      if (hasVerkey()) {
        hash = (37 * hash) + VERKEY_FIELD_NUMBER;
        hash = (53 * hash) + getVerkey().hashCode();
      }
      if (hasLength()) {
        hash = (37 * hash) + LENGTH_FIELD_NUMBER;
        hash = (53 * hash) + getLength().hashCode();
      }
      if (hasIdentifier()) {
        hash = (37 * hash) + IDENTIFIER_FIELD_NUMBER;
        hash = (53 * hash) + getIdentifier().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static protobuf.SegmentPB.Segment parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static protobuf.SegmentPB.Segment parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static protobuf.SegmentPB.Segment parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static protobuf.SegmentPB.Segment parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static protobuf.SegmentPB.Segment parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static protobuf.SegmentPB.Segment parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static protobuf.SegmentPB.Segment parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static protobuf.SegmentPB.Segment parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static protobuf.SegmentPB.Segment parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static protobuf.SegmentPB.Segment parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static protobuf.SegmentPB.Segment parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static protobuf.SegmentPB.Segment parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(protobuf.SegmentPB.Segment prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code protobuf.Segment}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:protobuf.Segment)
        protobuf.SegmentPB.SegmentOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return protobuf.SegmentPB.internal_static_protobuf_Segment_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return protobuf.SegmentPB.internal_static_protobuf_Segment_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                protobuf.SegmentPB.Segment.class, protobuf.SegmentPB.Segment.Builder.class);
      }

      // Construct using protobuf.SegmentPB.Segment.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        type_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        sender_ = "0";
        bitField0_ = (bitField0_ & ~0x00000002);
        receiver_ = "1";
        bitField0_ = (bitField0_ & ~0x00000004);
        data_ = "0";
        bitField0_ = (bitField0_ & ~0x00000008);
        dchecksum_ = "0";
        bitField0_ = (bitField0_ & ~0x00000010);
        signature_ = "0";
        bitField0_ = (bitField0_ & ~0x00000020);
        schecksum_ = "0";
        bitField0_ = (bitField0_ & ~0x00000040);
        pubkey_ = "";
        bitField0_ = (bitField0_ & ~0x00000080);
        verkey_ = "";
        bitField0_ = (bitField0_ & ~0x00000100);
        length_ = "";
        bitField0_ = (bitField0_ & ~0x00000200);
        identifier_ = "";
        bitField0_ = (bitField0_ & ~0x00000400);
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return protobuf.SegmentPB.internal_static_protobuf_Segment_descriptor;
      }

      @java.lang.Override
      public protobuf.SegmentPB.Segment getDefaultInstanceForType() {
        return protobuf.SegmentPB.Segment.getDefaultInstance();
      }

      @java.lang.Override
      public protobuf.SegmentPB.Segment build() {
        protobuf.SegmentPB.Segment result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public protobuf.SegmentPB.Segment buildPartial() {
        protobuf.SegmentPB.Segment result = new protobuf.SegmentPB.Segment(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.type_ = type_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.sender_ = sender_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.receiver_ = receiver_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.data_ = data_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.dchecksum_ = dchecksum_;
        if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
          to_bitField0_ |= 0x00000020;
        }
        result.signature_ = signature_;
        if (((from_bitField0_ & 0x00000040) == 0x00000040)) {
          to_bitField0_ |= 0x00000040;
        }
        result.schecksum_ = schecksum_;
        if (((from_bitField0_ & 0x00000080) == 0x00000080)) {
          to_bitField0_ |= 0x00000080;
        }
        result.pubkey_ = pubkey_;
        if (((from_bitField0_ & 0x00000100) == 0x00000100)) {
          to_bitField0_ |= 0x00000100;
        }
        result.verkey_ = verkey_;
        if (((from_bitField0_ & 0x00000200) == 0x00000200)) {
          to_bitField0_ |= 0x00000200;
        }
        result.length_ = length_;
        if (((from_bitField0_ & 0x00000400) == 0x00000400)) {
          to_bitField0_ |= 0x00000400;
        }
        result.identifier_ = identifier_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof protobuf.SegmentPB.Segment) {
          return mergeFrom((protobuf.SegmentPB.Segment)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(protobuf.SegmentPB.Segment other) {
        if (other == protobuf.SegmentPB.Segment.getDefaultInstance()) return this;
        if (other.hasType()) {
          setType(other.getType());
        }
        if (other.hasSender()) {
          bitField0_ |= 0x00000002;
          sender_ = other.sender_;
          onChanged();
        }
        if (other.hasReceiver()) {
          bitField0_ |= 0x00000004;
          receiver_ = other.receiver_;
          onChanged();
        }
        if (other.hasData()) {
          bitField0_ |= 0x00000008;
          data_ = other.data_;
          onChanged();
        }
        if (other.hasDchecksum()) {
          bitField0_ |= 0x00000010;
          dchecksum_ = other.dchecksum_;
          onChanged();
        }
        if (other.hasSignature()) {
          bitField0_ |= 0x00000020;
          signature_ = other.signature_;
          onChanged();
        }
        if (other.hasSchecksum()) {
          bitField0_ |= 0x00000040;
          schecksum_ = other.schecksum_;
          onChanged();
        }
        if (other.hasPubkey()) {
          bitField0_ |= 0x00000080;
          pubkey_ = other.pubkey_;
          onChanged();
        }
        if (other.hasVerkey()) {
          bitField0_ |= 0x00000100;
          verkey_ = other.verkey_;
          onChanged();
        }
        if (other.hasLength()) {
          bitField0_ |= 0x00000200;
          length_ = other.length_;
          onChanged();
        }
        if (other.hasIdentifier()) {
          bitField0_ |= 0x00000400;
          identifier_ = other.identifier_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        if (!hasType()) {
          return false;
        }
        if (!hasSender()) {
          return false;
        }
        if (!hasReceiver()) {
          return false;
        }
        if (!hasData()) {
          return false;
        }
        if (!hasDchecksum()) {
          return false;
        }
        if (!hasSignature()) {
          return false;
        }
        if (!hasSchecksum()) {
          return false;
        }
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        protobuf.SegmentPB.Segment parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (protobuf.SegmentPB.Segment) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int type_ = 0;
      /**
       * <code>required .protobuf.Segment.SegmentType type = 1 [default = NONE];</code>
       */
      public boolean hasType() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required .protobuf.Segment.SegmentType type = 1 [default = NONE];</code>
       */
      public protobuf.SegmentPB.Segment.SegmentType getType() {
        @SuppressWarnings("deprecation")
        protobuf.SegmentPB.Segment.SegmentType result = protobuf.SegmentPB.Segment.SegmentType.valueOf(type_);
        return result == null ? protobuf.SegmentPB.Segment.SegmentType.NONE : result;
      }
      /**
       * <code>required .protobuf.Segment.SegmentType type = 1 [default = NONE];</code>
       */
      public Builder setType(protobuf.SegmentPB.Segment.SegmentType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000001;
        type_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>required .protobuf.Segment.SegmentType type = 1 [default = NONE];</code>
       */
      public Builder clearType() {
        bitField0_ = (bitField0_ & ~0x00000001);
        type_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object sender_ = "0";
      /**
       * <code>required string sender = 2 [default = "0"];</code>
       */
      public boolean hasSender() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required string sender = 2 [default = "0"];</code>
       */
      public java.lang.String getSender() {
        java.lang.Object ref = sender_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            sender_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string sender = 2 [default = "0"];</code>
       */
      public com.google.protobuf.ByteString
          getSenderBytes() {
        java.lang.Object ref = sender_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          sender_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string sender = 2 [default = "0"];</code>
       */
      public Builder setSender(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        sender_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string sender = 2 [default = "0"];</code>
       */
      public Builder clearSender() {
        bitField0_ = (bitField0_ & ~0x00000002);
        sender_ = getDefaultInstance().getSender();
        onChanged();
        return this;
      }
      /**
       * <code>required string sender = 2 [default = "0"];</code>
       */
      public Builder setSenderBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        sender_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object receiver_ = "1";
      /**
       * <code>required string receiver = 3 [default = "1"];</code>
       */
      public boolean hasReceiver() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>required string receiver = 3 [default = "1"];</code>
       */
      public java.lang.String getReceiver() {
        java.lang.Object ref = receiver_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            receiver_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string receiver = 3 [default = "1"];</code>
       */
      public com.google.protobuf.ByteString
          getReceiverBytes() {
        java.lang.Object ref = receiver_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          receiver_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string receiver = 3 [default = "1"];</code>
       */
      public Builder setReceiver(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        receiver_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string receiver = 3 [default = "1"];</code>
       */
      public Builder clearReceiver() {
        bitField0_ = (bitField0_ & ~0x00000004);
        receiver_ = getDefaultInstance().getReceiver();
        onChanged();
        return this;
      }
      /**
       * <code>required string receiver = 3 [default = "1"];</code>
       */
      public Builder setReceiverBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        receiver_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object data_ = "0";
      /**
       * <code>required string data = 4 [default = "0"];</code>
       */
      public boolean hasData() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>required string data = 4 [default = "0"];</code>
       */
      public java.lang.String getData() {
        java.lang.Object ref = data_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            data_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string data = 4 [default = "0"];</code>
       */
      public com.google.protobuf.ByteString
          getDataBytes() {
        java.lang.Object ref = data_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          data_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string data = 4 [default = "0"];</code>
       */
      public Builder setData(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        data_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string data = 4 [default = "0"];</code>
       */
      public Builder clearData() {
        bitField0_ = (bitField0_ & ~0x00000008);
        data_ = getDefaultInstance().getData();
        onChanged();
        return this;
      }
      /**
       * <code>required string data = 4 [default = "0"];</code>
       */
      public Builder setDataBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        data_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object dchecksum_ = "0";
      /**
       * <code>required string dchecksum = 5 [default = "0"];</code>
       */
      public boolean hasDchecksum() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <code>required string dchecksum = 5 [default = "0"];</code>
       */
      public java.lang.String getDchecksum() {
        java.lang.Object ref = dchecksum_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            dchecksum_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string dchecksum = 5 [default = "0"];</code>
       */
      public com.google.protobuf.ByteString
          getDchecksumBytes() {
        java.lang.Object ref = dchecksum_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          dchecksum_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string dchecksum = 5 [default = "0"];</code>
       */
      public Builder setDchecksum(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
        dchecksum_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string dchecksum = 5 [default = "0"];</code>
       */
      public Builder clearDchecksum() {
        bitField0_ = (bitField0_ & ~0x00000010);
        dchecksum_ = getDefaultInstance().getDchecksum();
        onChanged();
        return this;
      }
      /**
       * <code>required string dchecksum = 5 [default = "0"];</code>
       */
      public Builder setDchecksumBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
        dchecksum_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object signature_ = "0";
      /**
       * <code>required string signature = 6 [default = "0"];</code>
       */
      public boolean hasSignature() {
        return ((bitField0_ & 0x00000020) == 0x00000020);
      }
      /**
       * <code>required string signature = 6 [default = "0"];</code>
       */
      public java.lang.String getSignature() {
        java.lang.Object ref = signature_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            signature_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string signature = 6 [default = "0"];</code>
       */
      public com.google.protobuf.ByteString
          getSignatureBytes() {
        java.lang.Object ref = signature_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          signature_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string signature = 6 [default = "0"];</code>
       */
      public Builder setSignature(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000020;
        signature_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string signature = 6 [default = "0"];</code>
       */
      public Builder clearSignature() {
        bitField0_ = (bitField0_ & ~0x00000020);
        signature_ = getDefaultInstance().getSignature();
        onChanged();
        return this;
      }
      /**
       * <code>required string signature = 6 [default = "0"];</code>
       */
      public Builder setSignatureBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000020;
        signature_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object schecksum_ = "0";
      /**
       * <code>required string schecksum = 7 [default = "0"];</code>
       */
      public boolean hasSchecksum() {
        return ((bitField0_ & 0x00000040) == 0x00000040);
      }
      /**
       * <code>required string schecksum = 7 [default = "0"];</code>
       */
      public java.lang.String getSchecksum() {
        java.lang.Object ref = schecksum_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            schecksum_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string schecksum = 7 [default = "0"];</code>
       */
      public com.google.protobuf.ByteString
          getSchecksumBytes() {
        java.lang.Object ref = schecksum_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          schecksum_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string schecksum = 7 [default = "0"];</code>
       */
      public Builder setSchecksum(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000040;
        schecksum_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string schecksum = 7 [default = "0"];</code>
       */
      public Builder clearSchecksum() {
        bitField0_ = (bitField0_ & ~0x00000040);
        schecksum_ = getDefaultInstance().getSchecksum();
        onChanged();
        return this;
      }
      /**
       * <code>required string schecksum = 7 [default = "0"];</code>
       */
      public Builder setSchecksumBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000040;
        schecksum_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object pubkey_ = "";
      /**
       * <code>optional string pubkey = 8;</code>
       */
      public boolean hasPubkey() {
        return ((bitField0_ & 0x00000080) == 0x00000080);
      }
      /**
       * <code>optional string pubkey = 8;</code>
       */
      public java.lang.String getPubkey() {
        java.lang.Object ref = pubkey_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            pubkey_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string pubkey = 8;</code>
       */
      public com.google.protobuf.ByteString
          getPubkeyBytes() {
        java.lang.Object ref = pubkey_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          pubkey_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string pubkey = 8;</code>
       */
      public Builder setPubkey(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000080;
        pubkey_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string pubkey = 8;</code>
       */
      public Builder clearPubkey() {
        bitField0_ = (bitField0_ & ~0x00000080);
        pubkey_ = getDefaultInstance().getPubkey();
        onChanged();
        return this;
      }
      /**
       * <code>optional string pubkey = 8;</code>
       */
      public Builder setPubkeyBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000080;
        pubkey_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object verkey_ = "";
      /**
       * <code>optional string verkey = 9;</code>
       */
      public boolean hasVerkey() {
        return ((bitField0_ & 0x00000100) == 0x00000100);
      }
      /**
       * <code>optional string verkey = 9;</code>
       */
      public java.lang.String getVerkey() {
        java.lang.Object ref = verkey_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            verkey_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string verkey = 9;</code>
       */
      public com.google.protobuf.ByteString
          getVerkeyBytes() {
        java.lang.Object ref = verkey_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          verkey_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string verkey = 9;</code>
       */
      public Builder setVerkey(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000100;
        verkey_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string verkey = 9;</code>
       */
      public Builder clearVerkey() {
        bitField0_ = (bitField0_ & ~0x00000100);
        verkey_ = getDefaultInstance().getVerkey();
        onChanged();
        return this;
      }
      /**
       * <code>optional string verkey = 9;</code>
       */
      public Builder setVerkeyBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000100;
        verkey_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object length_ = "";
      /**
       * <code>optional string length = 10;</code>
       */
      public boolean hasLength() {
        return ((bitField0_ & 0x00000200) == 0x00000200);
      }
      /**
       * <code>optional string length = 10;</code>
       */
      public java.lang.String getLength() {
        java.lang.Object ref = length_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            length_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string length = 10;</code>
       */
      public com.google.protobuf.ByteString
          getLengthBytes() {
        java.lang.Object ref = length_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          length_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string length = 10;</code>
       */
      public Builder setLength(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000200;
        length_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string length = 10;</code>
       */
      public Builder clearLength() {
        bitField0_ = (bitField0_ & ~0x00000200);
        length_ = getDefaultInstance().getLength();
        onChanged();
        return this;
      }
      /**
       * <code>optional string length = 10;</code>
       */
      public Builder setLengthBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000200;
        length_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object identifier_ = "";
      /**
       * <code>optional string identifier = 11;</code>
       */
      public boolean hasIdentifier() {
        return ((bitField0_ & 0x00000400) == 0x00000400);
      }
      /**
       * <code>optional string identifier = 11;</code>
       */
      public java.lang.String getIdentifier() {
        java.lang.Object ref = identifier_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            identifier_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string identifier = 11;</code>
       */
      public com.google.protobuf.ByteString
          getIdentifierBytes() {
        java.lang.Object ref = identifier_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          identifier_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string identifier = 11;</code>
       */
      public Builder setIdentifier(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000400;
        identifier_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string identifier = 11;</code>
       */
      public Builder clearIdentifier() {
        bitField0_ = (bitField0_ & ~0x00000400);
        identifier_ = getDefaultInstance().getIdentifier();
        onChanged();
        return this;
      }
      /**
       * <code>optional string identifier = 11;</code>
       */
      public Builder setIdentifierBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000400;
        identifier_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:protobuf.Segment)
    }

    // @@protoc_insertion_point(class_scope:protobuf.Segment)
    private static final protobuf.SegmentPB.Segment DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new protobuf.SegmentPB.Segment();
    }

    public static protobuf.SegmentPB.Segment getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<Segment>
        PARSER = new com.google.protobuf.AbstractParser<Segment>() {
      @java.lang.Override
      public Segment parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Segment(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Segment> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Segment> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public protobuf.SegmentPB.Segment getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_protobuf_Segment_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_protobuf_Segment_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\rsegment.proto\022\010protobuf\"\330\003\n\007Segment\0221\n" +
      "\004type\030\001 \002(\0162\035.protobuf.Segment.SegmentTy" +
      "pe:\004NONE\022\021\n\006sender\030\002 \002(\t:\0010\022\023\n\010receiver\030" +
      "\003 \002(\t:\0011\022\017\n\004data\030\004 \002(\t:\0010\022\024\n\tdchecksum\030\005" +
      " \002(\t:\0010\022\024\n\tsignature\030\006 \002(\t:\0010\022\024\n\tschecks" +
      "um\030\007 \002(\t:\0010\022\016\n\006pubkey\030\010 \001(\t\022\016\n\006verkey\030\t " +
      "\001(\t\022\016\n\006length\030\n \001(\t\022\022\n\nidentifier\030\013 \001(\t\"" +
      "\332\001\n\013SegmentType\022\010\n\004NONE\020\000\022\010\n\004NEXT\020\001\022\t\n\005E" +
      "RROR\020\014\022\n\n\006ACCEPT\020\002\022\n\n\006REJECT\020\003\022\023\n\017REQUES" +
      "T_CONNECT\020\004\022\016\n\nDISCONNECT\020\005\022\017\n\013REQUEST_K" +
      "EY\020\006\022\014\n\010SEND_KEY\020\007\022\020\n\014SEND_MESSAGE\020\010\022\r\n\t" +
      "SEND_FILE\020\t\022\030\n\024REQUEST_SEND_MESSAGE\020\n\022\025\n" +
      "\021REQUEST_SEND_FILE\020\013B\013B\tSegmentPB"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_protobuf_Segment_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_protobuf_Segment_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_protobuf_Segment_descriptor,
        new java.lang.String[] { "Type", "Sender", "Receiver", "Data", "Dchecksum", "Signature", "Schecksum", "Pubkey", "Verkey", "Length", "Identifier", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
